[package]
name = "meth_parms"
version = "0.1.0"
authors = ["crupib <crupib@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
